import React, { useEffect, useState } from "react";
import axios from "axios";
import names from "../assets/names.json";

const surnames = [
  "Wulflander",
  "Duskbattler",
  "Flarewarrior",
  "Gazerelf",
  "Spearmoor",
  "Rainland",
  "Seaoak",
  "Glideflare",
  "Batlips",
  "Plainsplains",
  "Falcongazer",
  "Brightwind",
  "Maceriver",
  "Starcape",
  "Warriorshort",
  "Waterrage",
  "Autumnore",
  "Bullbow",
  "Birdhunter",
  "Banebat",
  "Greenworm",
  "Gazeworm",
  "Winterchase",
  "Ramnight",
  "Baneglide",
  "Axduskmane",
  "Moonbear",
  "Greyyellow",
  "Ironmightred",
  "Longeye",
  "Bulllake",
  "Boltmagenta",
  "Picker",
  "Dragonblack",
  "Capeforge",
  "Daggerblur",
  "Wulfdragon",
  "Firewolf",
  "Mawax",
  "Hairblack",
  "Lightspring",
  "Ram",
  "Rage-eagle",
  "Wallshield",
  "Lakeleaf",
  "Battlesteel",
  "Mightsunlock",
  "Moondragon",
  "Fullfall",
  "Brightflare",
  "Walkgatesummer",
  "Hawkman",
  "Nosemetal",
  "Hearteagle",
  "Golddawn",
  "Nightdawn",
  "Greyore",
  "Cyanax",
  "Blueforge",
  "White",
  "Oreland",
  "Batlake",
  "Macemourne",
  "Eyemetalglide",
  "Goatscream",
  "Redsheep",
  "Huntergaze",
  "Landersea",
  "Capegazer",
  "Landerroad",
  "Mournlocke",
  "Starwarrior",
  "Riveriron",
  "Warriorsun",
  "Screambolt",
  "Quivergliderelf",
  "Lynxstaff",
  "Blurfury",
  "Bloodstorm",
  "Breezecape",
  "Mightblack",
  "Ironlockelips",
  "Maceelven",
  "Rain-warrior",
  "Bolteyes",
  "Paladin",
  "Treeelf",
  "Plainshair",
  "Pickerhame",
  "Shadowmight",
  "Blurwave",
  "Moorblack",
  "Steelred",
  "Magentawarg",
  "Iron-lock",
  "Blueshade",
  "Helmmaw",
  "Elfmoon",
  "Chasetongue",
  "Starbush",
  "Treepower",
  "Silveryellowcat",
  "Goldblue",
  "Hammer",
  "Hair",
  "Manefall",
  "Goatbreeze",
  "Leaf",
  "Wormgaze",
  "Bladeeye",
  "Earspear",
  "Wintertall",
  "Manbow",
  "Whitebright",
  "Riverscream",
  "Goldsilver",
  "Sideboar",
  "Morningwolf",
  "Steellake",
  "Lakefire",
  "Elfman",
  "Bearwyrm",
  "Steeltree",
  "Longborne",
  "Sheepdwarf",
  "Might",
  "Furyside",
  "Glide",
  "Breakergreen",
  "Metalmaze",
  "Rainshield",
  "Halfmace",
  "Moonmace",
  "Fallcat",
  "Furymace",
  "Bravebright",
  "Shadeforce",
  "Forgeeagle",
  "Lordlander",
  "Nosewave",
  "Flareworm",
  "Jawmaze",
  "Short",
  "Lynxbronze",
  "Elf",
  "Riverbreaker",
  "Mournbear",
  "Spearside",
  "Firesun",
  "Arrowhunt",
  "Falconworm",
  "Green",
  "Brightdawn",
  "Eaglebird",
  "Shadowmawblood",
  "Battlerbow",
  "Gazergreen",
  "Cyanchase",
  "Silverpower",
  "Sandsummer",
  "Halfpicker",
  "Autumnglidehalf",
  "Greenjaw",
  "Bronzewind",
  "Gaze-river",
  "Morningblue",
  "Eagleriver",
  "Ragedagger",
  "Silver",
  "Wall",
  "Hellthunder",
  "Sealand",
  "Silvermight",
  "Wavewar",
  "Bladeautumn",
  "Hiltbear",
  "Bowhunt",
  "Lightshadow",
  "Hiltdwarf",
  "Dagger",
  "Walllong",
  "Gazewyrm",
  "Tallhoundstorm",
  "Boltlong",
  "Dayspringhunter",
  "Powermoon",
  "Blueax",
  "Moorpower",
  "Shadowwarrior",
  "Elvenbat",
  "Shinesand",
  "Landwarrior",
  "Spearwave",
  "Yellowfalcon",
  "Darkhunter",
  "Morningaxbird",
  "Nightwarrior",
  "Halfglider",
  "Elvenshade",
  "Bow",
  "Walkwarrior",
  "Wyrmriver",
  "Landwar",
  "Gazereye",
  "Spearmagenta",
  "Heartram",
  "Lightwave",
  "Battlermoor",
  "Blackmightdark",
  "Wulfbreak",
  "Speartall",
  "Iron-heart",
  "Leafplains",
  "Sandbreeze",
  "Silverwall",
  "Goatnight",
  "Fullwall",
  "Lockdusk",
  "Daggerstorm",
  "Daysheepriver",
  "Hellmetal",
  "Thundersheep",
  "Long",
  "Thunderbird",
  "Borneram",
  "Springbush",
  "Moonoaken",
  "Earstaff",
  "Mangoldwalk",
  "Landwalker",
  "Huntdark",
  "Paladinblur",
  "Sideforge",
  "Boar",
  "Sungate",
  "Walkboar",
  "Oreflame",
  "Shadestorm",
  "Warglander",
  "Brightdragon",
  "Screamsun",
  "Axcloakbull",
  "Lightroad",
  "Shadeforge",
  "Bronzemagenta",
  "Elffalldragon",
  "Rainnose",
  "Goldax",
  "Warriorcat",
  "Moonblade",
  "Nightquiver",
  "Daggerglaze",
  "Rain",
  "Lordbreak",
  "Morning",
  "Wulfmourne",
  "Bravesea",
  "Daggernight",
  "Tallshade",
  "Daggermagenta",
  "Runnerpicker",
  "Lipswar",
  "Paladin",
  "Starglaze",
  "Orewall",
  "Hunterfalldusk",
  "Landdawn",
  "Flarehilt",
  "Roadwalker",
  "Daggermane",
  "Moonarrow",
  "Lipsbattle",
  "Shade-summer",
  "Powerworm",
  "Blursheep",
  "Moosewyrm",
  "Plains",
  "Axemight",
  "Rageshort",
  "Goldwhite",
  "Hillside",
  "Bull",
  "Helmhair",
  "Runnerspine",
  "Shadecloak",
  "Oakenwalker",
  "Short-power",
  "Staffsteel",
  "Storm-eyes",
  "Axbright",
  "Houndquiver",
  "Roadfull",
  "Oakfall",
  "Eyes",
  "Earfall",
  "Axequiver",
  "Macemountain",
  "Stormbitter",
  "Sidelight",
  "Dawnhammer",
  "Staffmoor",
  "Firelocke",
  "Hairgrey",
  "Bushtall",
  "Greydwarf",
  "Summerriver",
  "Glazegaze",
  "Firelynx",
  "Windlight",
  "Breakermaze",
  "Treehalf",
]

const AddCardName = () => {
  const [name, setName] = useState("");
  const [nameStart, setNameStart] = useState("");
  const [nameFinish, setNameFinish] = useState("");
  const [namesDB, setNamesDB] = useState("");

  const postName = async (name) => {
    let response = await axios.post("http://localhost:1337/names", {
      name: name,
    });
    console.log(response.data);
  };

  const postSurname = async (surname) => {
    let response = await axios.post("http://localhost:1337/surnames", {
      surname: surname,
    });
    console.log(response.data);
  };

  const filteredNames = (start, finish) => {
    return names.filter((name, id) => id >= start && id <= finish);
  };

  const filterdSurnames = (start, finish) => {
    return surnames.filter((name, id) => id >= start && id <= finish);
  };


  return (
    <>
      <div className="import-Names">
        <div className="controls">
          <span className="flex-center">
            <input
              type="text"
              placeholder={nameStart}
              size="5"
              onChange={(e) => setNameStart(e.target.value)}
            />
          </span>
          <span>
            <input
              type="text"
              placeholder={nameFinish}
              size="5"
              onChange={(e) => setNameFinish(e.target.value)}
            />
          </span>
          <button
            onClick={() => {
              filterdSurnames(nameStart, nameFinish).map((item) => postSurname(item));
            }}
          >
            criar nomes
          </button>

        <h1>{surnames.length}</h1>
        </div>

        <div className="list">
          {filterdSurnames(nameStart, nameFinish).map((item, id) => (
            <p key={id}>{item}</p>
          ))}
        </div>
      </div>
    </>
  );
};

export default AddCardName;
